# Generated by Django 5.0 on 2024-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
